import type { Metadata } from "next";
import { LegalShell, LegalSection } from "@/components/legal-shell";

export const metadata: Metadata = {
  title: "Privacy Policy — FlowForge",
  description: "How FlowForge collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy" updated="January 2, 2026">
      <p>
        This Privacy Policy explains how FlowForge (&ldquo;FlowForge&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) collects,
        uses, and protects information when you use our website and our managed n8n automation and
        hosting services (the &ldquo;Services&rdquo;). By using the Services, you agree to the practices
        described here.
      </p>

      <LegalSection heading="1. Information we collect">
        <p>We collect the following categories of information:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li><strong>Account information</strong> — name, email address, company, and billing details you provide when you contact us or sign up.</li>
          <li><strong>Workflow configuration</strong> — the automations you ask us to build, including the third-party services and endpoints they connect to.</li>
          <li><strong>Credentials</strong> — API keys, tokens, and connection secrets you authorize us to use on your behalf, stored encrypted at rest.</li>
          <li><strong>Usage data</strong> — execution counts, run history, error logs, and performance metrics generated by your hosted workflows.</li>
          <li><strong>Technical data</strong> — IP address, browser type, and device information collected automatically when you visit our site.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="2. How we use your information">
        <p>We use the information we collect to:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>Design, build, host, and maintain your automation workflows.</li>
          <li>Connect your workflows to the APIs and services you authorize.</li>
          <li>Monitor performance, send alerts, and troubleshoot issues.</li>
          <li>Calculate usage-based billing and process payments.</li>
          <li>Provide support and communicate with you about the Services.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="3. Workflow data and credentials">
        <p>
          Data that passes through your workflows is processed solely to execute the automations you
          have requested. We do not sell it or use it to train models. Credentials are encrypted in
          transit and at rest, scoped to your tenant, and revocable at any time.
        </p>
      </LegalSection>

      <LegalSection heading="4. Third-party services">
        <p>
          Your workflows integrate with third-party providers (for example Slack, Stripe, or your own
          APIs). Data shared with those providers is governed by their respective privacy policies. We
          also rely on infrastructure and payment sub-processors that meet industry security standards.
        </p>
      </LegalSection>

      <LegalSection heading="5. Cookies">
        <p>
          Our website uses essential cookies for basic functionality and preference storage (such as
          your light/dark theme). We do not use advertising cookies.
        </p>
      </LegalSection>

      <LegalSection heading="6. Data retention">
        <p>
          We retain account and configuration data for as long as your engagement is active and for a
          reasonable period afterwards to meet legal and accounting obligations. Execution logs are
          retained on a rolling basis according to your plan. You may request deletion at any time.
        </p>
      </LegalSection>

      <LegalSection heading="7. Security">
        <p>
          We use encryption, tenant isolation, access controls, and audit logging to protect your data.
          No method of transmission or storage is completely secure, but we work to protect your
          information using industry-standard safeguards.
        </p>
      </LegalSection>

      <LegalSection heading="8. International transfers">
        <p>
          We can host your workflows in EU or US regions. Where data is transferred across borders, we
          rely on appropriate safeguards such as standard contractual clauses.
        </p>
      </LegalSection>

      <LegalSection heading="9. Your rights">
        <p>
          Depending on your location, you may have the right to access, correct, export, or delete your
          personal data, and to object to certain processing. To exercise these rights, contact us using
          the details below.
        </p>
      </LegalSection>

      <LegalSection heading="10. Changes to this policy">
        <p>
          We may update this Privacy Policy from time to time. Material changes will be posted on this
          page with an updated date.
        </p>
      </LegalSection>

      <LegalSection heading="11. Contact us">
        <p>
          Questions about this policy? Email <a className="text-indigo-500 hover:underline" href="mailto:privacy@flowforge.example">privacy@flowforge.example</a>.
        </p>
      </LegalSection>
    </LegalShell>
  );
}
